name: License headers
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - uses: ruby/setup-ruby@eab2afb99481ca09a4e91171a8e0aee0e89bfedd # v1.300.0
      with:
        ruby-version: 3
    - name: Check license headers
      run: |
        ruby ./.github/check_license_headers.rb
