name: Lint
on: [push, pull_request]
jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@eab2afb99481ca09a4e91171a8e0aee0e89bfedd # v1.296.0
        with:
          ruby-version: 2.5
      - run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          ruby -v
          bundle install
          bundle exec rubocop
